version: "3.9"
services:
  misc-php-file-expolits:
    container_name: misc-php-file-expolits
    build:
      context: ../../../
      dockerfile: challenges/misc/php-file-expolits/Dockerfile
    networks:
      nw0:
    command: bash start_php.sh

networks:
  nw0:
    external: true
