name: File Upload
description: |
  This is a challenge that familiarizes you with exploits in the PHP file inclusion and file upload functionalities.
  This CTF needs you to know the following:
  Knowledge on a generic website's structure.
  Basic Website Injection techniques.
  Basic Knowledge of Linux file system commands.

  **Connection Instructions**:
  
  Do the following:

  $ ssh -L localhost:<local port>:container_ip:container_port -p 56151 <username>@cs561.cs.umass.edu

  For example, run

  $ ssh -L localhost:8080:172.20.26.4:80 -p 56151 user@cs561.cs.umass.edu

  This will forward the local port 8080 on your machine to 172.20.26.4:80 on the swarm network, where this challenge is hosted.

  You can try going to localhost:8080 on your browser to see if the forwarding has worked.

  Challenge 1: Exploit a vulnerability in the given PHP file inclusion functionality.
  Challenge 2: Exploit a vulnerability in the given PHP file upload functionality.

value: 100
category: Miscellaneous
flag: CTF_SDaT{f1l3_inclu510n_vuln3r4b1l1ty_@nd_uPload_3xplo1t}

# administrative
container_name: misc-php-file-expolits
